theori-io/nrsc5

- src/decode.c
The tail-biting portion of `calc_cber` takes the wrong bits from the end of the decoded message, so errors are reported when none are present. After this change, I now see a BER of 0.000000 when receiving a strong signal instead of ~0.000022.
> Fix off-by-one in calc_cber.

- src/output.c
Currently, program service data is only displayed for the main program. Ports 0x5201 to 0x5207 are used for the secondary programs (HD2, HD3, etc). See table 5-2 in http://www.nrscstandards.org/sg/nrsc-5-c/1019sg.pdf
/cc @KeyserSoze1
> Allow SPSD ports 0x5201 to 0x5207.

- src/defines.h
The current `U8_Q15` macro causes a couple problems when the input signal level approaches or exceeds full scale. First, an input sample of 255 is mapped to (255-127)<<8 which wraps to -32768, introducing distortion. Second, the `firdecim_q15` filter produces an output signal that has a higher maximum amplitude than the input signal, and so it needs some breathing room. Both problems can be solved by lowering the gain of `U8_Q15`. After this change, I was able to successfully receive even when the `-g` parameter was set a bit too high.
> Decrease gain of U8_Q15 to mitigate clipping.

- src/decode.c
- src/input.c
Section 14.2.2 of http://www.nrscstandards.org/SG/NRSC-5-C/1011sG.pdf specifies that the transmitter's output signal is conjugated, inverting the frequency spectrum. Doing the same in the receiver eliminates the need to read out the bits in reverse order.
> Invert spectrum to simplify receiver.

- src/frame.c
Prior to this change, my local station's fixed data wasn't decoding because the extended hybrid frames did not contain fixed data, but has_fixed thought they did.
> Fix has_fixed.

- CMakeLists.txt
Currently it's not possible to rebuild the project without a network connection because github needs to be checked for updates. Adding a `GIT_TAG` for id3v2lib solves the problem.
> Add git tag for id3v2lib.

- src/frame.c
Some stations (e.g. KQRT in Las Vegas) don't include a Header Expansion Field. Currently `find_program` returns -1 in this case, because it doesn't know what to do when the Header Expansion Flag is 0.
In that case there is only one program (number 0), so we should just check whether the user asked for program number 0.
> Handle PDUs that don't have a Header Expansion Field.

- src/sync.c
This brings back the other change I had proposed in #22.
Searching a window wider than 76 subcarriers is likely to select the wrong subcarrier, at least in primary modes 11, 5 and 6 (which have four extra reference subcarriers towards the middle).
This still allows for a ppm error as high as +/- 125.
> Reduce CFO search window size to 76 subcarriers.

- src/frame.c
When the BER is high, the PDU header can be corrupted. This can result in a segfault when data is read past the end of the PDU buffer. I've corrected the problem by adding length checks before reading the Header Expansion and PSD bytes.
It's likely that this fixes #16.
> Add length checks to frame_process.

- src/acquire.c
The current pulse shaping window function is raised to the power 2. The one specified in http://www.nrscstandards.org/SG/NRSC-5-C/2646s02.pdf Appendix A is not squared. I don't believe the squaring is necessary, because the transmitter also has its own pulse shaping window function (http://www.nrscstandards.org/SG/NRSC-5-C/1011sG.pdf section 13.2) and the combined effect of the two filters produces the desired squaring.
I tested this against my nrsc-5 transmitter and removing the extra squaring improved the MER by about 1 dB from ~21 to ~22 dB.
> Correct the pulse shaping window function.

- README.md
- src/main.c
Fixes #50.
This change allows the frequency to be specified either in MHz or Hz. If the number is greater than 10,000 it will be interpreted as Hz, otherwise as MHz. I chose that threshold because the RTL-SDR can't tune that high (in MHz) or that low (in Hz).
If the frequency is entered as `107.1M` (like `rtl_fm`) then the trailing `M` is simply ignored and it's interpreted as 107.1 MHz.
> Accept frequency in MHz or Hz.

- src/input.c
Fixes #51 (and hopefully also #53).
I tracked down the reason the receiver stops after 48 minutes. It's because `cfo_idx` (a 32-bit signed integer) overflows, wrapping around to a negative number, at which point `st->cfo_idx++ % FFT` becomes negative, causing out-of-bounds accesses to `st->cfo_tbl` here:
https://github.com/theori-io/nrsc5/blob/b9acf8eb439e8a1ba783065aa9dd7c991d5bac12/src/input.c#L97
I've solved this by reducing `cfo_idx` mod `FFT` after the loop.
/cc @classicjazz
> Fix cfo_idx integer overflow.

- src/main.c
If the input file is not a multiple of four bytes (which is often the case for files produced by my [gr-nrsc5 project](https://github.com/argilo/gr-nrsc5)) then nrsc5 exits with an assertion failure. That's because the `input_cb` function requires its input to be a multiple of four bytes:
https://github.com/theori-io/nrsc5/blob/1bd3f793abadf9645c7bb54c65178001f27a307c/src/input.c#L277
To make sure that requirement is always satisfied, I've changed the `fread` to read four bytes at a time.
> Read the input file four bytes at a time.

- src/decode.c
- src/decode.h
- src/pids.c
- src/pids.h
Fixes #43.
Currently SIS logging is very noisy. To solve this, I'm proposing to log only when a PDU contains new values.
/cc @pclov3r @itdaniher
> Only log SIS messages when there's a change.

- src/output.c
- src/output.h
Implements #44, a log message showing the audio bit rate (averaged over the last 32 audio packets).
Sample output:
```
$ src/nrsc5 98.1 1 2>&1 | grep bit
15:13:55 DEBUG output.c:117: Audio bit rate: 31.1 kbps
15:13:56 DEBUG output.c:117: Audio bit rate: 30.6 kbps
15:13:58 DEBUG output.c:117: Audio bit rate: 30.4 kbps
15:13:59 DEBUG output.c:117: Audio bit rate: 30.3 kbps
15:14:01 DEBUG output.c:117: Audio bit rate: 31.4 kbps
```
@pclov3r
> Log audio bit rate.

- src/output.c
@docprofsky Here's a simpler fix for the OS X compile issue you ran into. Does this work for you?
> Replace clock_gettime with more portable gettimeofday.

- src/input.c
- src/input.h
- src/main.c
Fixes #52.
The automatic gain selection code was slow, and seemed unnecessarily complicated. It used an FFT to compare the power of the digital sidebands to the power of the noise around them, and tried to maximize that ratio.
I've simplified it to just increase the input gain until the input power reaches 10 dB less than full scale. The extra 10 dB leaves some breathing room in case the signal strength increases after automatic gain selection finishes.
I also reduced the number of input samples used to make each measurement, which speeds up the time for automatic gain selection to just over one second in the worst case.
/cc @classicjazz
> Simplify and speed up automatic gain selection.

- CMakeLists.txt
- src/CMakeLists.txt
- src/config.h.in
- src/output.c
ID3v2 is not a complicated format, and HD Radio only uses a subset of it. So it seems like it's worth removing the id3v2lib dependency and implementing the parts of ID3v2 that are needed right in nrsc5. This PR implements enough to decode title, artist and album. I tested on a bunch of stations and it seems to work properly.
/cc @KeyserSoze1
> Remove id3v2lib dependency.

- .travis.yml
@awesie What do you think about adding Travis CI? I tried this in my fork, and it works well: https://travis-ci.org/argilo/nrsc5
I've configured it to build on Linux & OS X using both gcc and clang. The `script` also runs nrsc5 to make sure that it's able to decode your sample file. A more extensive test script could be added in the future.
> Integrate with Travis CI.

- src/decode.c
- src/decode.h
The convolutional encoder for P3 doesn't start producing valid output until it's seen two full frames of input. To account for this, I've modified `decode_process_p3` so it only starts producing output once the interleaver's internal matrix is filled up. This should reduce the risk of crashes or other bad behaviour during startup.
> Wait for P3 interleaver internal matrix to fill up.

- src/frame.c
- src/frame.h
Currently, when nrsc5 starts receiving it logs several "psd crc mismatch" messages. This occurs because neither `parse_psd` nor `process_fixed_block` waits for an HDLC flag (0x7E) before starting up. As a result, they pass partial PDUs to `aas_push`.
To correct this problem, I've changed them both to use an index of -1 to indicate that the first HDLC flag has not yet been seen. Once an HDLC flag is seen, they set their index to 0 and carry on with normal processing.
It's a bit easier to see what I've changed with whitespace changes excluded: https://github.com/theori-io/nrsc5/compare/fix-aas-start?w=1
> Delay processing of AAS PDUs until first HDLC flag is seen.

- src/pids.c
- src/pids.h
This adds SIS message type 6, Service Information Message, which encodes information about the available audio and data services. For my local station it prints the following:
```
21:40:30 DEBUG pids.c:291: Data service: public, type 65, MIME type 5b6
21:40:30 DEBUG pids.c:291: Data service: public, type 259, MIME type eb2
21:40:30 DEBUG pids.c:291: Data service: public, type 259, MIME type 469
21:40:30 DEBUG pids.c:291: Data service: public, type 66, MIME type 2d7
21:40:30 DEBUG pids.c:291: Data service: public, type 66, MIME type e96
21:40:30 DEBUG pids.c:269: Audio program 0: public, type 8, sound experience 0
21:40:30 DEBUG pids.c:269: Audio program 1: public, type 4, sound experience 0
21:40:30 DEBUG pids.c:269: Audio program 2: public, type 3, sound experience 0
```
For details see …
> Implement Service Information Message.

- src/defines.h
- src/input.c
- src/input.h
- src/main.c
It's apparent from @pclov3r's report #81 that the new automatic gain selection method doesn't always work well. This PR reverts the change, but also reduces the number of FFTs performed by the automatic gain selection from 3072 to 256, so it should be just as fast as it was after my change.
@pclov3r How does this work for you?
> Go back to the old gain selection method.

- src/acquire.c
OFDM timing synchronization fails about 5% of the time, because it only searches for the start of a symbol over the range 0-2047, even though it could occur at any sample offset from 0 to 2159. Running the following command demonstrates the problem:
```
xz -d < ../support/sample.xz | tail -c +561 | src/nrsc5 -r - 0
```
To fix this, I've expanded the search window to include the entire range (i.e. the duration of one symbol, including cyclic prefix).
> Search for symbol synchronization over the whole period.

- src/decode.c
- src/output.c
- src/output.h
Audio stutter often occurs at the start of live audio playback, because NRSC-5's audio codec has a variable bit rate, but nrsc5 doesn't account for that.
To solve the problem, I've added 10 packets worth of silence to the beginning of the audio. I chose 10 because it's the maximum allowed elastic buffer depth. See http://www.nrscstandards.org/sg/nrsc-5-d-reference-docs/1017s.pdf section 4.3 for details.
> Prevent audio stutter by adding silence to start of live audio

- src/frame.c
- src/frame.h
Currently `frame_process` waits for an audio packet with sequence number 0 to come along before it starts passing audio packets along for decoding. This can add up to a couple seconds to the start-up time.
As far as I know, the sequence numbers are simply indexes into a 64-frame circular buffer that a player could use. There's nothing special about sequence number 0, so I don't see any reason to wait for it to arrive. Everything seems to work fine after this change.
When combined with #95 this brings the acquisition time down pretty close to the theoretical minimum.
> Play audio packets immediately; don't wait for number 0.

- src/firdecim_q15.c
I found an off-by-one error in firdecim_q15's `push` function. When it reaches the end of its window, it copies the wrong samples back to the beginning.
I tested with recordings of 14 stations, and in all cases the BER was improved.
> Fix off-by-one error in firdecim_q15 push.

- src/defines.h
- src/sync.c
I noticed that the reported MER is 0.8 dB low for stations using primary mode 3, because the signal is assumed to come from only 10 partitions, whereas the noise is summed from all 12. I corrected this simply by changing `P1_DATA_PER_BAND` to `partitions_per_band * 18`.
Since `P1_DATA_PER_BAND` was no longer used, I removed it from defines.h, and I also got rid of `P1_BAND_LENGTH` (which was barely used).
Finally, I changed the MER display to include only one decimal place. (Previously it showed the default six.)
Here's an example for a recording of my local station. Before:
```
08:31:27 INFO  sync.c:315: MER: 10.645880 dB (lower), 10.632761 dB (upper)
08:31:28 INFO  sync.c:315: MER: 10.610696 dB (lower), 10.569898 dB (upper)
08:31:28 INFO  sync.c:315: MER: 10.646533 dB (lower), 10.668467 …
```
> Fix MER calculation for primary mode 3.

- src/input.c
I noticed that I should have used `cq15_to_cf` for the type conversion in #95. Fixing that now.
> Use cq15_to_cf for conversion.

- src/acquire.c
Cheaper RTL-SDR dongles that lack a TCXO can drift quite a bit (~10 ppm) in frequency as they warm up. Currently nrsc5 doesn't account for this; it expects the frequency offset to remain nearly constant.
To fix this, I've changed the frequency tracking code to calculate the difference between the angles of `max_v` and `cexpf(I * st->prev_angle)` and adjust the angle using that value. That allows the angle to wrap around the full circle multiple times if necessary to track the drift of the RTL-SDR's oscillator.
Also I changed the smoothing factor from 0.5 to 0.1 as this made a significant improvement to the BER of the 15 recordings I use for tests.
> Improve frequency tracking.

- src/acquire.c
- src/acquire.h
- src/input.c
- src/input.h
- src/main.c
- src/sync.c
- src/sync.h
Most OFDM receivers use pre-FFT synchronization only during acquisition, then switch to post-FFT synchronization. This PR adds post-FFT synchronization to nrsc5. The change improves the bit error rate across all recordings I tested with.
Since post-FFT synchronization requires feedback to pass from `sync.c` back to `acquire.c` (preferably immediately) I decided to remove the input and sync threads. I believe they were only added to make reception possible on multi-core ARM processors, but performance has since been improved in other ways. (The output thread is still useful so that signal processing can continue even when audio output is blocked, so I left it in place.)
I also managed a significant speedup (especially on ARM) by replacing the complex exponentiation in `acquire_process` …
> Implement post-FFT synchronization.

- src/main.c
The CNR value displayed during automatic gain selection is off by a factor of two.
I also changed the display to include only a single decimal place.
Gain selection now looks like so:
```
22:23:36 INFO  main.c:61: Gain: 0.0 dB, CNR: 21.5 dB
22:23:36 INFO  main.c:61: Gain: 0.9 dB, CNR: 25.4 dB
22:23:36 INFO  main.c:61: Gain: 1.4 dB, CNR: 26.3 dB
22:23:36 INFO  main.c:61: Gain: 2.7 dB, CNR: 28.9 dB
22:23:36 INFO  main.c:61: Gain: 3.7 dB, CNR: 28.8 dB
22:23:36 INFO  main.c:61: Gain: 7.7 dB, CNR: 29.8 dB
22:23:37 INFO  main.c:61: Gain: 8.7 dB, CNR: 30.5 dB
22:23:37 INFO  main.c:61: Gain: 12.5 dB, CNR: 30.0 dB
22:23:37 INFO  main.c:61: Gain: 14.4 dB, CNR: 30.0 dB
22:23:37 INFO  main.c:61: Gain: 15.7 dB, CNR: 30.2 dB
22:23:37 INFO  main.c:61: Gain: 16.6 dB, CNR: 30.7 dB
22:23:37 INFO …
```
> Fix the CNR calculation, and only display one decimal place.

- src/acquire.c
- src/defines.h
- src/sync.c
This fixes a regression observed by @awesie in https://github.com/theori-io/nrsc5/pull/108#issuecomment-344143640
The new post-FFT synchronization code was performing sub-optimally for non-TCXO dongles, because it assumed the sample clock error to be zero. To correct this, I've added code to estimate the sample clock error and add a corresponding amount to the symbol timing error (`samperr`) to compensate. This accounts for the number of samples that will be gained or lost between invocations of `acquire_process`.
The sample clock error is estimated by performing a linear regression on the `prev_slope` values. The slope gives the sample clock error, while the intercept (already computed as `angle`) gives the frequency error.
After this change, the bit error rate either improved (in some …
> Compensate for sample clock error in post-FFT sync.

- README.md
- src/log.c
User on [reddit](https://www.reddit.com/r/RTLSDR/comments/7b742x/can_anyone_cross_compile_this_linux_hd_radio/) was very confused about how to build this on Windows. This adds complete instructions for building it on Windows with dependencies.
I also added a fflush to log.c, otherwise log messages not flushed to the console in real-time on Windows.
> Add build instructions for Windows

- src/acquire.c
I just noticed I introduced a bug in #114. I forgot to update the length of the `memmove` in `acquire_process` when I changed the buffer to `cint16_t`.
> Fix the length of a memmove.

- src/acquire.c
- src/sync.c
- src/sync.h
Currently nrsc5 uses an ad-hoc method for BPSK synchronization. Switching to a Costas loop improves the BER for all recordings I tested with. On average, the improvement is 21%.
Also, I added an extra `cfo` parameter to `adjust_ref` to compensate for the rotation introduced by the carrier frequency offset. This simplifies the Costas loop implementation, and removes the need to invert the data in `find_ref`.
The Costas loop processes symbols one at a time (rather than in blocks of 32), which should allow for some future simplifications (such as removing `input_set_skip`).
Testing would be appreciated @classicfm @classicjazz @tylert @pclov3r.
> Use a Costas loop for synchronization.

- src/output.c
- src/output.h
Hopefully this solves #115.
This change does a few things:
* log the port number for files
* store the service data type and program number for each port
* for files with service data type 0x40, only write when the program number matches the current one
Traffic & weather files will still be written out regardless of the current program number.
This code is based on my reverse engineering assumptions from #115. Testing would be appreciated @cmnybo.
> Only write album art & station logo for the current program.

- src/sync.c
- src/sync.h
This is just some code cleanup. I've removed a bunch of unused stuff (`BUFS`, `dump_ref`, `ref_buf`, `buf_idx`, `used`) and switched `buffer` and `phases` to two-dimensional array syntax.
BER values are the same before & after the change for all my test files, so it appears this change hasn't broken anything.
> Clean up sync code

- src/acquire.c
When reading from a file, the center frequency is not set, which results in an invalid PPM value being printed:
```
10:19:25 INFO  acquire.c:163: CFO: 3997.100830 Hz (-2147483648 ppm)
```
This PR removes the PPM part of the message when the center frequency is not set.
> Don't display CFO PPM when reading from file.

- src/input.c
Samples recorded during automatic gain selection are not particularly useful, since there are time gaps between each gain level due to the `rtlsdr_reset_buffer` calls.
This PR changes `input_cb` so it doesn't start writing samples until automatic gain selection is complete.
> Don't write samples duing automatic gain selection.

- .travis.yml
This is a quick fix for the Travis CI build on OS X. The `brew install` step currently fails because of a conflict between gcc and oclint.
> Uninstall oclint to fix travis build on OSX.

- src/main.c
Fixes #136.
The `-d` argument was not working, because its value was not passed into `rtlsdr_open`.
Sorry for the delay in fixing this @ImDroided.
> Open the device specified by the -d argument.

- src/output.c
Decode the XHDR ID3 field according to information found online and experimentation. "MIME hash" appears to be a function of what is being transmitted (album art, logo, etc.), and is constant across multiple stations. "Parameter ID" is used to control what should be displayed -- "0" means "album art", "1" means either "blank screen" or "display the station logo". "Value" is currently opaque -- my theory is that it's correlated to the file to be displayed (either its name, or possibly some metadata), but I haven't been able to decode it further.
> improved XHDR decoding

- src/main.c
- src/output.c
@awesie's comment in https://github.com/theori-io/nrsc5/pull/141#issuecomment-457061952 prompted me to check for large stack allocations (with `-fstack-usage`). The worst offender by far was `uint8_t tmp[RADIO_BUFFER];` at 512 kB, followed by `input_t input;` at 52 kB. I've changed these both to heap allocations, and threw in `output_t output;` (2 kB) with them.
The program now happily runs with `ulimit -s 128`.
> Move large stack allocations to the heap.

- src/frame.c
This change addresses the following compiler warning:
```
/home/travis/build/argilo/nrsc5/src/frame.c: In function ‘process_fixed_data’:
/home/travis/build/argilo/nrsc5/src/frame.c:434:13: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
if (subch->block_idx == 4 && *(uint32_t *)subch->blocks != BBM)
^
```
I expect the old code would only work on little-endian systems.
> Use memcmp to check BBM.

- src/frame.c
- src/output.c
I found some more cases like #144 where assumptions about endianness were made. I tested the changes by running nrsc5 on the PowerPC architecture (in qemu).
> Read integers without assumptions about endianness.

- src/conv_dec.c
- src/conv_gen.h
- src/decode.c
- src/defines.h
- src/firdecim_q15.c
- src/frame.c
- src/hdc_to_aac.c
- src/output.c
- src/pids.c
- src/reed-solomon.c
- src/sync.c
I turned on `-Wall -Wextra -Wpedantic` to see what was lurking and fixed everything that came up: unused arguments and functions, signed/unsigned comparisons, and use of GNU extensions.
> Address compiler warnings.

- .travis.yml
The `-f` option no longer exists, so I had to adjust my Travis CI script accordingly.
> Remove obsolete command-line option.

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- src/private.h
Fixes #160. Fixes #161.
This change switches from POSIX calls back to the standard C library for file input. I changed the API to accept a file pointer instead of a file descriptor. Things appear to be working well on Windows now, and I tested to make sure "pipe" input is still working.
Getting rid of the pipe also saves us an ifdef (from #156) and eliminates system calls.
I guess it's worth considering whether `nrsc5_open_pipe` and `nrsc5_pipe_samples` are still sensible names, since the underlying pipe was just an implementation detail. I guess they do still let you pipe in samples, in some sense.
> Switch back to stdio for file reading.

- .gitignore
- .travis.yml
- CMakeLists.txt
- support/win-cross-compile
I've put together a shell script (`support/win-cross-compile`) to cross-compile Windows binaries on Linux. This has the advantage of being much faster than MSYS2, and allows Windows builds to be tested in Travis CI, which should help catch bugs like https://github.com/theori-io/nrsc5/pull/156 earlier.
To run the script, first install the MinGW compiler with `sudo apt install mingw-w64`, then run `support/win-cross-compile 32` to build 32-bit binaries or `support/win-cross-compile 64` to build 64-bit binaries. The output files will be in `build-win32/bin` or `build-win64/bin`.
I've tested this on Ubuntu 16.04 (through Travis CI) and Ubuntu 18.04. @pclov3r I'd be interested to hear if this works on Debian for you.
I'll add some documentation to the readme soon.
> Add script to cross-compile for Windows.

- src/CMakeLists.txt
- src/main.c
- src/output.c
- src/pids.c
- src/unicode.c
- src/unicode.h
Both SIS messages and ID3 tags in PSD have a character encoding associated with them, either ISO-8859-1 or UCS-2. So far nrsc5 has been ignoring the coding and printing out the raw bytes. This PR adds functions to convert from these encodings to UTF-8, and calls them where appropriate.
I was able to test ISO-8859-1 in ID3 directly because a local station sometimes uses non-ASCII characters. For the other cases I was only able to verify that ASCII messages were still displayed correctly. I haven't observed any stations using UCS-2.
I tested the `iso_8859_1_to_utf_8` and `ucs_2_to_utf_8` in a stand-alone program to verify that they work properly.
The `ucs_2_to_utf_8` function assumes little-endian when there is no Byte Order Mark since SIS specifies little-endian for UCS-2. ID3 can use …
> Support character encodings in SIS and PSD.

- support/msys2-build
- support/win-cross-compile
As @pclov3r suggested in https://github.com/theori-io/nrsc5/pull/159, I've added the `--enable-avx` option to FFTW when building it for Windows. I did some timings with PowerShell's `Measure-Command` and it seems to give a speedup of around 3% on my laptop. Debian also compiles its FFTW package with `--enable-avx` so that's another good indication it's safe to use.
> Enable AVX when building FFTW on Windows.

- src/defines.h
- src/frame.c
- src/frame.h
I noticed occasional "RS corrected 5 symbols" log messages even when listening to stations with a BER of zero, so I dug in to see what was going wrong. The problem is that the main loop in `frame_process` continues until it reaches the end of the PDU. If the PDU ends with fixed data, then the loop attempts to process it as if it was an audio packet. Usually this causes Reed-Solomon error correction to fail, but occasionally it succeeds and prints the "RS corrected 5 symbols" message. Audio packet processing then proceeds with bogus data.
To solve the problem I modified `process_fixed_data` to return the length of the PDU minus the amount of bytes it processed. Once it determines the lengths of the fixed data streams, the excess processing of audio packets stops.
Along the way I renamed …
> Avoid stepping into fixed data when processing audio payload.

- .travis.yml
- CMakeLists.txt
- README.md
- src/CMakeLists.txt
- src/libnrsc5.map
- src/libnrsc5.sym
- src/nrsc5.c
- support/msys2-build
- support/win-cross-compile
This PR moves most of the logic to build external libraries to CMake instead of scripts. Its primarily targeted at cross compiling and building for Windows, since libao's dynamic plugins make it difficult to statically link on other platforms. I have not tested building with the built-in libraries on Linux yet.
There are also some changes to speed up the Travis CI build using ccache and parallel make jobs. It also tests the built Windows binary using wine on macOS.
> Build dependencies using CMake

- .gitignore
- .travis.yml
- support/cli.py
- support/nrsc5.py
To make Python development easier, I created a Python API (which wraps the C API), then rewrote the Python CLI app to use it. To exercise the API (both Python and C) I implemented almost all the features of the C CLI app, and added logging for SIG events as well. The Python CLI uses the same arguments as the C CLI.
This PR builds on top of #174 because the uninitialized XHDR values were preventing MIME values from being put into the `MIMEType` enum.
> Create a Python API and improve the Python CLI app

- src/acquire.c
- src/frame.c
- src/input.c
- src/input.h
- src/sync.c
- src/sync.h
Fixes #172.
Since three components are now concerned with synchronization state, I've moved it out into the input struct. There are now three states:
* `SYNC_STATE_NONE` - not synchronized
* `SYNC_STATE_COARSE` - coarse synchronization has completed
* `SYNC_STATE_FINE` - fine synchronization has completed
If the reference subcarriers are not as expected or a frame fails to decode, then the state is set back to `SYNC_STATE_NONE`.
I'm still testing this out and would appreciate feedback. Testing instructions are available in #172. The amount of dropped samples can be changed by increasing or decreasing the number in the `tail` command. (Make sure the number remains odd, because each IQ sample is two bytes long.)
> Start over from coarse sync if frame can't be decoded.

- support/cli.py
- support/nrsc5.py
This should make it harder to use the API incorrectly.
> Require the caller to ensure input length is a multiple of 4.

- include/nrsc5.h
- src/libnrsc5.map
- src/libnrsc5.sym
- src/main.c
- src/nrsc5.c
- support/cli.py
- support/nrsc5.py
It seems like querying the version of the nrsc5 library could be a useful thing, so I pushed the version number checking over to the other side of the API and made an `nrsc5_get_version` API call.
The Python CLI now has a `-v` flag, like the C version.
> Get nrsc5 version through the API.

- src/frame.c
I'm experimenting with addressing #177, and to start I thought it would be useful to decode the remainder of the audio PDU header fields. These are described in Figure 5-2 and Table 5-1 in 1017s.pdf.
I also re-ordered the list to match Table 5-1 and changed the HEF calculation to return 0 or 1 (instead of 0 or 0x80 currently).
> Decode all header fields from audio PDUs.

- src/acquire.c
- src/decode.c
- src/defines.h
- src/input.c
- src/input.h
- src/nrsc5.c
This PR does two things:
1. Remove a bunch of magic numbers and replace them with constants.
2. Fix the SNR calculation used for AGC. The indices of the upper noise band were one too low, and so the first FFT bin included some of the signal. Also, the reported CNR values were off by a factor of 2; we're comparing powers and not amplitudes.
> Remove magic numbers and fix SNR calculation.

- src/sync.c
At the moment, there are two places in `sync_process` that call `input_set_skip`:
https://github.com/theori-io/nrsc5/blob/965be89f9d7d2f21222c285e6b79dadb832e60b6/src/sync.c#L212-L249
If the first block that arrives happens to be block 0, line 215 executes. Then block 1 arrives before the input has been skipped and line 239 executes, requesting the same skip a second time. Synchronization is then delayed until `cfo_wait` counts down to zero and line 239 executes a second time. This behaviour can be reproduced like so:
```
$ xz -d < ../support/sample.xz | tail -c +2700001 | src/nrsc5 -r - 0
07:51:19 DEBUG sync.c:214: First block @ 9
07:51:19 DEBUG sync.c:242: Block @ 9
07:51:19 DEBUG sync.c:242: Block @ 23
07:51:19 INFO  sync.c:219: Synchronized!
```
A similar situation occurs if block 15 …
> Prevent input_set_skip from occurring twice.

- src/frame.c
- src/output.c
We need to subtract 3 from the length because we skip the first byte and
ignore the last two bytes. This resolves the FIXMEs in output.c because we no
longer have the extraneous byte at the end.
> Fix off-by-one when passing AAS data to output.

- src/acquire.c
- src/acquire.h
During coarse synchronization, `acquire_process` uses a rectangular (in the time domain) filter to detect the OFDM cyclic suffix. This is sub-optimal because the transmitter's pulse-shaping filter gives the beginning & end of the OFDM symbol a non-rectangular shape. To correct this, I've switched to a matched filter by multiplying in the beginning & end of the pulse-shaping filter.
To test, I forced coarse synchronization to be used all the time and compared the performance before and after this change using my suite of IQ recordings. There was a slight improvement in both BER and number of frames decoded, and one weak station that was previously unreceivable now works (albeit with a high BER).
> Use a matched filter for coarse sync.

- src/main.c
This adds logging of SIG data in tho C CLI. This functionality is already present in the Python CLI.
Here's how it looks for a local station:
```
13:42:43 DEBUG main.c:298: SIG Service: type=audio number=1 name=MAJIC 100.3
13:42:43 DEBUG main.c:305:   Audio component: id=0 port=0 type=7 mime=4DC66C5A
13:42:43 DEBUG main.c:311:   Data component: id=1 port=2048 service_data_type=265 type=3 mime=BE4B7536
13:42:43 DEBUG main.c:311:   Data component: id=3 port=2049 service_data_type=265 type=3 mime=D9C72536
13:42:43 DEBUG main.c:298: SIG Service: type=audio number=2 name=580 CFRA on 100.3 HD2
13:42:43 DEBUG main.c:305:   Audio component: id=0 port=1 type=4 mime=4DC66C5A
13:42:43 DEBUG main.c:311:   Data component: id=1 port=2050 service_data_type=265 type=3 mime=BE4B7536
13:42:43 DEBUG …
```
> Log SIG data in the C CLI.

- include/nrsc5.h
- src/decode.c
- src/main.c
- src/nrsc5.c
- src/pids.c
- src/pids.h
- src/private.h
- support/cli.py
- support/nrsc5.py
Fixes #176.
This pull request adds Station Information Service (SIS) messages to the nrsc5 API (both C and Python).
Each time a new SIS message is received, the entire struct containing all SIS messages received so far is reported. This is a bit noisy for the current C & Python CLI applications, but seems appropriate for GUI applications.
"Station Name - long format" and "Station Slogan" messages are both returned in the `slogan` field (with Station Slogan taking precedence) since the NRSC-5 spec says that the long station name is deprecated in favor of slogan. (Some stations send the same data in both messages.)
A few things are not included in the API because I didn't think they were useful enough:
* ALFN
* Priority field for Station Message
* Control Data for Emergency Alert Message
* …
> Add SIS messages to the API.

- include/nrsc5.h
- src/acquire.c
- src/defines.h
- src/input.c
- src/input.h
- src/libnrsc5.map
- src/libnrsc5.sym
- src/nrsc5.c
- support/cli.py
- support/nrsc5.py
The `nrsc5_pipe_samples` function currently takes unsigned 8-bit samples at a sample rate of 1488375 Hz. This is convenient for the RTL-SDR but not for other SDRs, many of which have an ADC resolution higher than 8 bits.
To solve this problem, I've split `nrsc5_pipe_samples` into two functions:
* `nrsc5_pipe_samples_cu8` which uses the current RTL-SDR format
* `nrsc5_pipe_samples_cu16` which accepts 16-bit signed samples at a sample rate of 744187.5 Hz
The new `nrsc5_pipe_samples_cu16` function puts samples straight into the input module's buffer bypassing the halfband filter / decimator. 
To test the new functions, I've added an `--iq-input-format` argument to the Python CLI which defaults to the old RTL-SDR format. I received samples into a FIFO using a USRP B200:
```
mkfifo samples …
```
> Add signed 16-bit sample input.

- src/acquire.c
- src/frame.c
- src/input.c
- src/input.h
- src/main.c
- src/sync.c
- support/cli.py
I noticed a couple problems with the reporting of synchronization state. First, loss of synchronization is not reported if it occurs in `frame_process`. Second, the synchronization state is logged in sync.c instead of main.c.
To fix these problems, I've created a new `input_set_sync_state` function which is called whenever the sync state needs to be updated. It reports sync events through the API where appropriate.
> Fix reporting of synchronization state.

- support/cli.py
- support/nrsc5.py
This fixes a small bug: the XHDR field was not displayed if `param` was zero. (This occurs when album art is displayed.)
> Display XHDR even when param is 0.

- src/main.c
- src/output.c
- support/cli.py
I noticed that AAS port numbers are not logged consistently; in most places they're printed as hexidecimal, but I used decimal when I added logging of SIG data. This changes the format to `%04X` everywhere.
> Always use hex when logging port numbers.

- src/sync.c
if sync is lost and then regained, PSD CRC errors and audio decoding errors often occur. This happens because the beginning portions of partial PSD & audio packets remain in the frame state, and are then combined with the trailing portions of partial PSD & audio packets from a non-consecutive frame. The 16-bit PSD CRC check prevents most of the bogus PSD packets from being processed, but bogus audio packets are always sent to the AAC decoder since the 8-bit CRCs only apply to the pieces, not the whole packet.
To fix the problem, I've added a `frame_reset` call when sync is acquired. I tested this by making an IQ recording where I disconnected & reconnected my antenna five times. Prior to this change, 23 PSD CRC errors and 5 audio decode errors occurred, and after the change no errors …
> Reset frame state when sync is acquired.

- src/main.c
Proof-of-concept for adding support for some basic commands like quit or change audio program. I only spent a few minutes on it, mainly to get something out there for feedback on resolving #73.
One issue is that the CLI doesn't keep track of valid program numbers to give user feedback if they select a missing program, though the recent SIS event support should make this possible.
Second issue is that there is still a delay because we don't buffer audio from programs that are not currently selected.
> Add simple keyboard commands to CLI.

- src/decode.c
- src/input.c
- src/sync.c
I profiled nrsc5 and made some optimizations to the parts that use the most CPU cycles. The result is a speedup of about 5%.
The most significant changes are in sync.c where I updated some loops to process only the FFT bins which might later be used (i.e. the ones that may contain digital subcarriers).
> Optimize a few things.

- src/conv_dec.c
- src/conv_neon.h
- src/conv_sse.h
NRSC-5 uses convolutional codes in tail-biting mode. Currently the convolutional decoder in nrsc5 performs two full passes of Viterbi decoding. This improves decoding, but doubles the computational cost. Extending the beginning & end of the trellis by 32 achieves the same decoding performance at much lower computational cost. Making this change improves the overall performance of nrsc5 by about 7%.
In this PR I've also removed the unused functions in conv_neon.h and conv_sse.h to silence compiler warnings.
> Speed up Viterbi decoding

- CMakeLists.txt
- support/libao-win-fix.patch
Fixes #207.
When opening a WAV file for writing, libao doesn't request binary mode. On Windows, this causes carriage return characters to be inserted into the output file before line feed characters, corrupting the file.
For now I've modified nrsc5 to patch libao's `ao_open_file` function. I'll propose the patch to libao and remove it from here if the patch is accepted upstream.
> Fix WAV file output on Windows

- CMakeLists.txt
GCC 9 with -O3, specifically with auto vectorization enabled, causes audio
corruption. I do not know how to find the root cause, so just disable the
extra optimizations for now.
Fixes #212.
> Compile FAAD2 with -O2 instead of -O3.

- src/defines.h
- src/output.c
- src/output.h
When nrsc5 is built with `-fsanitize=undefined` to detect undefined behavior, some errors appear:
```
/home/argilo/git/nrsc5/src/input.c:173:18: runtime error: left shift of negative value -9
/home/argilo/git/nrsc5/src/input.c:171:18: runtime error: left shift of negative value -57
/home/argilo/git/nrsc5/src/input.c:172:18: runtime error: left shift of negative value -33
/home/argilo/git/nrsc5/src/input.c:174:18: runtime error: left shift of negative value -53
/home/argilo/git/nrsc5/src/output.c:401:79: runtime error: left shift of 190 by 24 places cannot be represented in type 'int'
/home/argilo/git/nrsc5/src/output.c:613:80: runtime error: left shift of 187 by 24 places cannot be represented in type 'int'
```
I made the necessary changes to avoid undefined behaviour and verified that …
> Fix undefined behavior

- CMakeLists.txt
Fixes issue 219 with appropriate Git repo for libao and adds timeouts for all external project adds capped to 2 minutes.
> Fixed issue 219: Corrected GIT REPO and Added Timeouts

- CMakeLists.txt
- README.md
- src/config.h.in
- src/log.c
- src/log.h
- support/cli.py
- support/msys2-build
Fixes #226.
As noted in #226, the log level, filename and line number are not particularly useful anymore and take up quite a bit of space. I agree with @awesie's suggestion to just get rid of them, which I've done here. I also removed `log_set_fp` as it is unused.
> Remove level, filename and line number from log

- src/sync.c
- src/sync.h
I noticed that #223 made CFO detection worse when there is a frequency error of more than a few parts per million. The reason is that `adjust_ref` is now called multiple times for each subcarrier as different CFO values are tried, and so the symbol phases get adjusted multiple times. To fix this, I added a `reset_ref` function to undo the phase adjustments after each offset is tried.
I also fixed some other problems with the synchronization code:
* The CFO frequency calculation in `adjust_ref` was incorrect.
* The `sync_reset` function didn't reset the Costas loop parameter for some of the subcarriers that were accessed during CFO detection. I changed it to reset all subcarriers.
* Checking the validity of the reference subcarriers is unnecessary in the `SYNC_STATE_FINE` state, since …
> Improve synchronization

- README.md
- include/nrsc5.h
- src/acquire.c
- src/acquire.h
- src/conv.h
- src/conv_dec.c
- src/conv_gen.h
- src/decode.c
- src/decode.h
- src/defines.h
- src/frame.c
- src/frame.h
- src/input.c
- src/input.h
- src/libnrsc5.map
- src/libnrsc5.sym
- src/main.c
- src/nrsc5.c
- src/output.c
- src/output.h
- src/private.h
- src/sync.c
- src/sync.h
- support/cli.py
- support/faad2-hdc-support.patch
- support/nrsc5.py
Resolves #33.
This adds basic support for receiving AM signals, as described in [NRSC-5 Layer 1 AM](https://www.nrscstandards.org/standards-and-guidelines/documents/standards/nrsc-5-d/reference-docs/1012s.pdf).
To use the new functionality, simply add the `--am` command line option.
Some limitations:
* Only the hybrid mode (MA1) is supported. Fortunately, almost all stations (except WWFD) are using this mode.
* Audio quality is sub-optimal, because only the "core" audio stream (20 kbps) is decoded. I don't yet know how to decode the packets in the "enhanced" audio stream, which contains an additional 16 kbps.
* Receive performance is sub-optimal. In particular, decimation and OFDM synchronization could be improved, and the Viterbi decoder could be switched from hard to soft decisions.
* …
> Add support for AM

- .travis.yml
- README.md
- include/nrsc5.h
- src/libnrsc5.map
- src/libnrsc5.sym
- src/main.c
- src/nrsc5.c
- src/rtltcp.c
- src/rtltcp.h
- support/cli.py
- support/nrsc5.py
Fixes #235.
Fixes #236.
`-T` enables the bias-T.
`-D 1` enables direct sampling on the I-ADC input
`-D 2` enables direct sampling on the Q-ADC input (which works with RTL-SDR Blog V3 dongles)
All the standard `rtl_*` utilities use `-T` for the bias-T, so that seemed like a good choice. The `rtl_power` tool uses `-D` for direct sampling, although without an argument to choose the input.
> Add support for bias-T & direct sampling

- support/faad2-hdc-support.patch
As @awesie noted in https://github.com/theori-io/nrsc5/issues/239#issuecomment-679113341, HDC block type 7 should be treated as stereo. I've made that change here, and can now decode audio from KSL.
> Add support for HDC block type 7

- CMakeLists.txt
- support/faad2-hdc-support.patch
The faad2 project seems to be alive again at https://github.com/knik0/faad2, and Debian is now using this fork. So I think it's worth switching nrsc5 over as well.
It seems that instead of using `--with-drm` to add DRM support, the project now just builds a libfaad_drm library in parallel with libfaad. I've mirrored this pattern and added a libfaad_hdc library which has HDC support.
> Change faad2 upstream and update to the latest

- src/frame.c
As noted in https://github.com/theori-io/nrsc5/pull/245#discussion_r484034638, partial PDUs are not handled correctly if one of the pieces has an invalid CRC. To correct this problem, I've done the following:
* remove the `continue` that was cutting the loop iteration short in the event of an invalid CRC
* add CRC checks around the steps that need to be skipped when the CRC is invalid
* always clear the "last" partial PDU (by resetting `pdu_idx` to zero) after processing the "first" partial PDU
> Fix handling of partial PDUs when CRC is invalid

- src/main.c
- support/cli.py
Fixes #267.
It appears that calling `rtlsdr_set_direct_sampling(st->dev, 0)` on an E4000 tuner does not work properly. To avoid the problem, we can simply avoid calling this function at all if the `-D` command line option is not used, rather than defaulting to setting the direct sampling mode to zero.
> Only call nrsc5_set_direct_sampling if -D is specified

- support/faad2-hdc-support.patch
Parametric Stereo (PS) is used to simulate stereo audio on low bandwidth
channels. Our decoding seems to cause audio distortions (#260) so
temporarily disable PS until we can fix the implementation.
> Disable parametric stereo

- src/conv_sse.h
Fixes #280.
When nrsc5 is compiled with GCC 12 and `-DUSE_SSE=1`, Viterbi decoding fails. A compiler warning points to the `_val` array as being the source of the problem. I expect that this is because casting it to a `double *` results in undefined behaviour. I've updated the code to manually duplicate the 8-bit inputs and then load them using an unaligned SSE load. After this change, `support/sample.xz` can be decoded properly.
I don't know much about SSE programming, so I'd appreciate a review from an expert. I'd also appreciate some help with testing @andrewfer000 @pclov3r @markjfine.
> Fix loading of SSE Viterbi decoder input

- .github/workflows/ci.yml
CI currently fails on macOS with the following error:
```
Traceback (most recent call last):
File "/Users/runner/work/nrsc5/nrsc5/support/cli.py", line 272, in <module>
cli = NRSC5CLI()
^^^^^^^^^^
File "/Users/runner/work/nrsc5/nrsc5/support/cli.py", line 18, in __init__
self.radio = nrsc5.NRSC5(lambda evt_type, evt: self.callback(evt_type, evt))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/runner/work/nrsc5/nrsc5/support/nrsc5.py", line 448, in __init__
self._load_library()
File "/Users/runner/work/nrsc5/nrsc5/support/nrsc5.py", line 346, in _load_library
NRSC5.libnrsc5 = ctypes.cdll.LoadLibrary(lib_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ctypes/__init__.py", line 454, in LoadLibrary …
```
> Temporarily disable Python tests on macOS

- src/sync.c
As noted in #287, nrsc5 fails to decode the P3 logical channel for stations that are using primary service mode 11 (MP11). This happens because primary service mode backward compatibility ([Layer 1 FM](https://www.nrscstandards.org/standards-and-guidelines/documents/standards/nrsc-5-d/reference-docs/1011s.pdf), section 6.2.1) is not implemented.
I've implemented that here, and the P3 logical channel should now be decoded for modes 3 and 11 (as well as reserved modes 27, 35, 43, 51, and 59; if any of these are added in the future, they will include a backwards compatible P3 logical channel).
After this change, the HD4 channel works in @markjfine's recording (https://github.com/theori-io/nrsc5/issues/287#issuecomment-1343161505).
> Add primary service mode backward compatibility

- src/decode.c
The Interleaver IV (section 10.2.6 of [Layer 1 FM](https://www.nrscstandards.org/standards-and-guidelines/documents/standards/nrsc-5-d/reference-docs/1011s.pdf)) implementation has a bug: the partition assignment counters vector `pt` is subject to integer overflow. This causes the P3 logical channel to stop decoding after about 8 hours and 45 minutes.
Here I've fixed the problem by resetting the `pt` vector to zero each time the internal interleaver matrix is filled.
> Fix integer overflow in partition assignment counters

- README.md
- src/main.c
As noted in #287, stations can have up to eight audio programs, but only the first four can be selected at runtime. Here I've added the remaining four.
> Allow all eight programs to be selected at runtime

- CMakeLists.txt
- support/faad2-hdc-support.patch
The proposed commit fixes the audio distortion problem with parametric stereo streams reported by #260 and also re-enables parametric stereo for HDC.  It also updates faad2 to the latest version.
Feel free to let me know if you see any additional changes in the DRM parametric stereo decoder that could be needed.
> Fix distortion with parametric stereo and re-enable parametric stereo

- README.md
You need the .rb or it does not work (for me anyway, on MacPro5,1 running Monterey).
> Fix Homebrew instructions

- README.md
- src/main.c
Due to Issue #279 regarding wav output stopping after about 3 hours  I added a flag "-P" to allow raw pcm output which should bypass any wav file limitations. It does require that you manually set the format and sample rate for consuming programs (with ffmpeg you can use s16le for format). I'm using this command to pipe to icecast2 with great results so far:
`nrsc5 -P -q -o - 94.3 0 | ffmpeg -re -ar 44100 -vn -ac 2 -channel_layout stereo -f s16le -i - -f ogg -c:a flac  -content_type 'application/ogg' icecast://source:PASSWORD@127.0.0.1:8000/radio`
> Adding ability to output raw pcm format in addition to wav

- src/conv.h
- src/conv_dec.c
- src/decode.c
- src/decode.h
- src/sync.c
Fixes #287.
@markjfine noticed that WWWT is using Service Mode MP11, which includes an additional logical data channel (P4). Here I've added support for this mode in two parts:
* fcd7ea7a80f53395e2447894d5eb3ab5772da2cc adds MP11 according to my reading of the NRSC-5 specification.
* d96b72c304f1902b4a762b632c8f56da6675f64a adds an additional delay block to the PX2 interleaver, which is necessary to receive WWWT's P4 logical data channel. (I reverse engineered its properties from WWWT's signal.)
I'm not sure why there's a mismatch between the specification and what WWWT is doing. Once more stations come online with MP11 signals, we should revisit this to see whether their signals are similar to WWWT's and decodable with the additional delay block in place.
I checked the new NRSC-5-E …
> Add support for Service Mode MP11

- src/main.c
Valgrind reports several errors if a key is pressed to switch between subchannels:
```
==3495671== Thread 3:
==3495671== Conditional jump or move depends on uninitialised value(s)
==3495671==    at 0x10F1D1: callback (in /home/argilo/git/nrsc5/build/src/nrsc5)
==3495671==    by 0x111951: output_aas_push (in /home/argilo/git/nrsc5/build/src/nrsc5)
==3495671==    by 0x11E8D6: frame_process (in /home/argilo/git/nrsc5/build/src/nrsc5)
==3495671==    by 0x1174CD: sync_process_fm (in /home/argilo/git/nrsc5/build/src/nrsc5)
==3495671==    by 0x11B3C0: acquire_process (in /home/argilo/git/nrsc5/build/src/nrsc5)
==3495671==    by 0x11382F: input_push (in /home/argilo/git/nrsc5/build/src/nrsc5)
==3495671==    by 0x110895: worker_thread (in /home/argilo/git/nrsc5/build/src/nrsc5)
==3495671==    by …
```
> Fix undefined behaviour in keyboard input

- src/pids.c
- src/pids.h
Recently I've started to see some stations using "Universal Short Station Name" in place of "Station Name - short format". The former supports names up to 12 characters long, as well as alternate character sets. This pull request adds support for USSN, allowing the names of these stations to be seen.
> Implement Universal Short Station Name

- src/input.c
For debugging purposes, it's useful to know what the current primary service mode is, since some stations are beginning to use modes other than 1 and 3. For instance, in #287 we found that WWWT was using mode 11, and I recently noticed that WAMU is using mode 2 (which is not yet supported by nrsc5).
Here I've added a debug log message so that we'll notice new modes more quickly.
> Log the primary service mode after synchronization

- src/pids.c
- src/pids.h
The "Station Message" payload has a checksum, but nrsc5 was ignoring it up until now. Here I've added checksum validation. I verified that it works correctly with all stations in my collection of 85 recordings.
> Implement checksum for Station Message

- src/conv.h
- src/conv_dec.c
- src/decode.c
- src/decode.h
- src/defines.h
- src/frame.c
- src/frame.h
- src/sync.c
Fixes #305.
This pull request does the following:
1. Adds support for primary service mode MP2. This mode is very similar to mode MP3, except that the P3 logical channel is only half as wide. Because of this difference, it also uses slightly different interleaver parameters. To accomodate this mode, I've added length arguments to some of the functions that process the P3 logical channel.
2. Adds support for fixed data in logical channels other than P1. To accommodate this, we need one CCC data structure per logical channel, and various functions have to pass around the current logical channel number.
3. Adds support for L2 PDUs containing only fixed data (and no audio).
All three enhancements were needed to properly receive WAMU, which uses mode MP2 and puts its station logos in data-only …
> Add support for primary service mode MP2

- src/output.c
- src/pids.c
- src/pids.h
The SIS long name & SIG service name fields are encoded as ISO-8859-1, which means that they must be converted to UTF-8 for display. After making this change, both fields are displayed properly:
```
17:45:41 Slogan: ICI R-C Première
17:45:41 SIG Service: type=ServiceType.AUDIO number=1 name=ICI R-C Première
```
> Convert long name & SIG service name to UTF-8

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- src/output.c
- src/output.h
- src/private.h
- support/cli.py
- support/nrsc5.py
There are three AAS data types used by HD Radio stations: Stream, Packet, and Large Object Transfer (LOT). Of these, only LOT files are currently exposed through the nrsc5 API. There is a bit of code in output.c aimed at decoding Stream data, but it is not functional.
Since there are various Stream data types (HERE TPEG, HERE Images, TTN TPEG) and Packet data types (HD TMC, NavteqPacketData1, NavteqAdmin) in use, I think it would make sense to expose the raw Stream & Packet payloads through the API, and make the consuming application responsible for decoding the data type(s) it cares about.
Here I've added `NRSC5_EVENT_STREAM` and `NRSC5_EVENT_PACKET` event types to the API. Each of these reports the 16-bit port number, payload size, 32-bit MIME hash (taken from the corresponding entry in …
> Expose stream & packet data through the API

- src/frame.c
L2 PDUs with header sequence CW4 contain only fixed data, and no audio. Audio packets should only be processed if the header sequence is CW0, CW1, CW2, or CW3.
> Skip audio processing in PDUs that only have fixed data

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- src/output.c
- src/output.h
- src/private.h
- support/cli.py
- support/nrsc5.py
In the initial implementation of LOT file decoding, a few fields from the protocol had unknown meaning. I've filled those in here.
One of the fields is an expiry time (in UTC) after which the file can be safely discarded. This seems useful to expose through the API, so I've added it. (In C it's provided as a `struct tm *`, and in Python it's a `datetime` object.)
> Report LOT expiry time in the API

- src/frame.c
Only suppress audio if we're certain it's a data-only PDU.
Fixes #312.
> Invert the has_audio check

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- src/output.c
- src/private.h
- support/cli.py
- support/nrsc5.py
AAS sequence numbers could be of use to users of the API. For stream data in particular, they could be used to detect lost data, which could trigger a reset of the stream processing.
> Expose AAS sequence numbers in the API

- include/nrsc5.h
- src/nrsc5.c
- src/output.c
- src/private.h
- support/nrsc5.py
In #310 a new member was added to the middle of the `lot` struct, which inadvertently broke [nrsc5-gui](https://github.com/cmnybo/nrsc5-gui), which has a copy of the `nrsc5.py` Python API shim. By moving the `expiry_utc` member to the end of the struct, binary compatibility can be preserved.
> Put the new expiry_utc member at the end of the lot struct

- src/acquire.c
- src/acquire.h
- src/decode.c
- src/decode.h
- src/frame.c
- src/rtltcp.c
Clang reports a number of warnings: one unused parameter, and many comparisons of signed and unsigned integers. I've cleaned those up here.
> Fix compiler warnings

- src/nrsc5.c
- src/private.h
- support/cli.py
- support/nrsc5.py
As noted in https://github.com/theori-io/nrsc5/issues/322#issuecomment-1694611094, it's annoying for API users that complex samples must be passed into `nrsc5_pipe_samples_cu8` two at a time (i.e. four bytes at a time). Here I've removed all length restrictions from `nrsc5_pipe_samples_cu8` and `nrsc5_pipe_samples_cs16` so that it's no longer even necessary to ensure that the I & Q pieces of a sample are passed in at the same time. Any leftover samples or pieces thereof are stored in a buffer until more input arrives.
@TheDaChicken Let me know if this simplifies things on your end.
> Remove input length restrictions from pipe API

- src/input.c
Fixes #329.
I had a look over the FFTW documentation, and as far as I can tell, it is not necessary to call `fftwf_cleanup`. In fact, doing so may cause trouble for API users, because `nrsc5_close` will trigger `fftwf_cleanup`, which could invalidate plans created outside nrsc5.
> Remove call to fftwf_cleanup

- CMakeLists.txt
Updating to rtl-sdr 2.0.1 picks up various bug fixes, and adds support for RTL-SDR Blog V4 devices.
I had to use a commit slightly newer than 2.0.1 to pick up this pkg-config fix: https://gitea.osmocom.org/sdr/rtl-sdr/pulls/4
> Update rtl-sdr to version 2.0.1

- CMakeLists.txt
Fixes #317.
FFTW and libusb have had various bug fixes since the versions originally used in nrsc5. We may as well pick up the latest.
* https://www.fftw.org/release-notes.html
* https://github.com/libusb/libusb/blob/master/ChangeLog
> Update external project versions

- src/decode.c
- src/decode.h
This was added in d96b72c304f1902b4a762b632c8f56da6675f64a to deal with WWWT's non-standard signal.
It's necessary to remove it to receive WTUE's MP11 signal, which follows the standard. I would hope that WWWT has already fixed their signal, but if not I suppose we could consider adding a command-line option to select the non-standard interleaving.
/cc @markjfine
> Remove non-standard MP11 interleaving

- src/acquire.c
- src/decode.c
- src/decode.h
- src/defines.h
- src/frame.c
- src/sync.c
Fixes #240.
Here I have implemented support for MA3, the all-digital AM service mode. I tested that it is able to receive WWFD, using a recording made with W3HFU's KiwiSDR. As with the MA1 hybrid mode, only the "core" audio stream is decoded, and the "enhanced" stream is discarded. (Improvements to the HDC decoder would be needed to decode the enhanced stream. See #245 for a previous attempt at that.) I was able to decode WWFD's station logo:
While working on this, I found a bug in gr-nrsc5's header spread calculations, which I fixed in https://github.com/argilo/gr-nrsc5/commit/c8b1b0f3deefc74ea628b683701909e03127ede6. After that change, I was also able to receive a synthesized MA3 signal generated by gr-nrsc5.
> Add MA3 (all digital) service mode

- include/nrsc5.h
- src/CMakeLists.txt
- src/nrsc5.c
This deals with a warning that Clion IDE gave me. 
`__declspec(dllexport)` is meant to be used in the header. 
Although CMake's newer versions can do this automatically using `set(CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS ON)`, we are still on CMake version 2.8. There is already a *DLLMarkup* so it should be okay.
> Move DLLMarkup to header 

- src/CMakeLists.txt
- src/acquire.c
- src/acquire.h
I recently noticed that nrcs5 reports a non-zero BER even for very strong signals (including synthetic signals generated by gr-nrsc5). I did a git bisect and found that the problem was introduced in #326. In particular, changing `fftcp` from `int` to `unsigned int` broke the phase calculation, which works with signed integers:
https://github.com/theori-io/nrsc5/blob/e6ae705ac211d8c7a0884a88c0f01179c7e6c822/src/acquire.c#L163
Here I reverted the change to unsigned types, and changed the corresponding loop indexes to signed integers so that no new warnings are produced. Strong signals now have zero BER, as expected.
> Fix signedness bug in OFDM synchronization

- src/acquire.c
- src/input.c
- src/nrsc5.c
- src/private.h
Fixes #349.
The `nrsc5_open()`, `nrsc5_open_file()`, `nrsc5_open_pipe()`, `nrsc5_open_rtltcp()`, and `nrsc5_close()` API functions call into FFTW functions which are not thread-safe. (See https://www.fftw.org/doc/Thread-safety.html for an explanation of thread safety in FFTW.)
To make nrsc5's API functions thread-safe, I have protected the affected FFTW calls with a mutex. After this change, I was able to initialize and run many instances of nrsc5 in parallel from Python without any crashes.
@luarvique I hope this change will make it simpler for OpenWebRX+ to use nrcs5.
> Make open and close functions thread-safe

- support/nrsc5.py
The C API allows additional data to be passed into the callback function through an opaque pointer:
https://github.com/theori-io/nrsc5/blob/a4b7883971a7eb1c555ff8a23194dd559abd9609/include/nrsc5.h#L589-L597
But the Python API doesn't have such a mechanism. It's possible to use closures, but that's not always convenient. So I've added an optional `callback_args` which will be passed through to the callback function. A tuple or list of arguments can be supplied.
> Allow additional callback arguments in Python API

- CMakeLists.txt
autoconf wants to install things into lib64 not lib by default on openSUSE
> Fix build on openSUSE 15.6

- include/nrsc5.h
- src/libnrsc5.map
- src/libnrsc5.sym
- src/main.c
- src/nrsc5.c
- src/pids.c
- src/pids.h
- src/private.h
- support/cli.py
- support/nrsc5.py
Fixes #358.
Emergency alert messages include "control data" bytes, which until now were ignored by nrsc5. The format of the control bytes is not publicly documented, but through reverse engineering I have determined the meaning of most data fields. The following data is now decoded:
* alert categories (up to 2), e.g. "Weather", "Safety", "Test"
* location code format: [SAME](https://en.wikipedia.org/wiki/Specific_Area_Message_Encoding), [FIPS](https://en.wikipedia.org/wiki/FIPS_county_code), or [ZIP](https://en.wikipedia.org/wiki/ZIP_Code)
* list of location codes (0-31)
I made this data, as well as the raw control bytes, available through the API. I also updated the C and Python CLI applications to display the data:
```
21:50:59 Alert: Category=[Weather] SAME=[27027, 27167] The National …
```
> Add decoding of emergency alert control bytes

- support/faad2-hdc-support.patch
nrsc5 occasionally crashes when corrupted HDC packets make it past the 8-bit CRC check and into faad2.
I intentionally fed fuzzed data into the decoder, and found that the crash always occurred at the `if (hDecoder->sbr[0]->ret)` line. Here `hDecoder->sbr[0]` can be null, leading to a null pointer dereference.
I added a null check, which fixes the crash. I also removed an unused variable to resolve a compiler warning.
I tested this change against my I/Q recording library, and didn't notice any change in behaviour.
> Fix null pointer dereference in faad2 patch

- src/sync.c
I recently compared nrsc5's low-SNR performance against a Sangean HDT-20, and found that the HDT-20 is able to go about 2 dB lower than nrsc5. The reason for the different seems to be that nrsc5 uses hard-decision decoding:
https://github.com/theori-io/nrsc5/blob/ddd097988b45fedaf5ff996c18a8e7e0c08ce1da/src/sync.c#L455
After switching to soft-decision decoding, nrsc5 appears to be on par with the HDT-20, and reception is reliable (i.e. no invalid HDC packets) all the way down to 4 dB SNR.
> Feed soft decisions into Viterbi decoder

- src/sync.c
Once coarse synchronization is completed, nrsc5 uses Costas loops to track the frequencies of the reference subcarriers. It uses their frequencies to estimate the OFDM timing and frequency error, and feeds this information back to the "acquire" stage.
I noticed that oscillation or unstable behaviour occurs if the initial coarse frequency estimate is inaccurate. In this case, the "sync" stage requests a relatively large frequency adjustment, but does not update the frequencies in its Costas loops to compensate for this change.
After adding code to adjust the Costas loop frequencies, the unstable behaviour went away. I also observed slightly better performance across my suite of recordings, with some additional audio packets decoded.
> Update Costas loop state when requesting a frequency adjustment

- src/defines.h
Currently nrsc5 uses two blocks (= 64 symbols) for coarse (i.e. pre-FFT) OFDM synchronization. This seems to be overkill, as the detected correlation peak remains strong even at 0 dB SNR where the data carried in QPSK subcarriers is not decodable. Switching to a single block (= 32 symbols) has negligible impact on the number of decoded audio packets. AM reception at low SNR suffers slightly, but only because it uses a poor design. (It should switch to using the AM carrier and reference subcarriers for synchronization, as intended.)
This change also removes an obstacle to implementing elastic buffering (#343): because the "acquire" stage presently operates two blocks at a time, and because the pair of blocks is not necessarily aligned with the start of a frame, one extra block of latency …
> Use 32 symbols for coarse acquisition

- src/nrsc5.c
Currently nrsc5 receives samples from the RTL-SDR in batches of 512 kB (= 262144 I/Q samples = 176 milliseconds). This adds a corresponding amount of latency (inconvenient for #380), and is somewhat problematic for elastic buffering (#343) since it forces audio output to occur in relatively large 176-ms bursts.
The RTL-SDR header file notes that the buffer length must be a multiple of 512 bytes, and should be a multiple of 16384 bytes. While testing the nrsc5 API, I found that reading samples in very small batches causes extra CPU overhead, but the effect becomes negligible once the batch size reaches 32768 bytes (= 16384 I/Q samples = 11 milliseconds). This seems like a reasonable buffer length to use.
To maintain the total amount of buffer space, I increased the number of buffers to …
> Reduce RTL-SDR buffer length

- src/decode.c
- src/decode.h
- src/sync.c
- src/sync.h
Fixes #380.
Currently, nrsc5 doesn't decode data from any of the logical channels until block 0 of a 16-block transfer frame arrives. This can take up to 1.4 seconds.
PIDS data arrives one block at a time, so we can begin decoding it as soon as synchronization is achieved. SIS data appears about a second after starting nrsc5.
P3 and P4 data arrives two blocks at a time, so we can begin decoding it as soon as an even-numbered block arrives. Audio still takes a few seconds to begin playing, because these logical channels use an interleaver that is 32 blocks long.
> Start decoding PIDS, P3, and P4 earlier

- src/acquire.c
- src/acquire.h
- src/input.c
- src/input.h
- src/sync.c
nrsc5 needs to maintain synchronization both with individual OFDM symbols, and with blocks (groups of 32 OFDM symbols). Currently the "acquire" stage takes care of the former. It has a 33-symbol buffer, and wants the first 32 of those symbols to be occupied by a block, and it carries over the 33rd symbol to the next invocation of `acquire_process`. But if the OFDM symbol alignment is off, it adjusts that carryover amount by up to +/- one half of a symbol, so that symbol alignment is restored.
https://github.com/theori-io/nrsc5/blob/4005811e2f2d95c1b37ff9f29d426f57daa3ae76/src/acquire.c#L257-L259
Meanwhile, when the "sync" stage finds which of the 32 OFDM symbols is the start of a block, it invokes `input_set_skip` to ask the "input" stage to discard that number of OFDM symbols, so that …
> Move block synchronization to the acquire stage

- src/main.c
Fixes #253.
nrsc5 can write binary data to stdout, or read binary data from stdin:
* `-o -` writes audio to stdout
* `-w -` writes I/Q to stdout
* `--dump-hdc -` writes HDC to stdout
* `-r -` reads I/Q from stdin
But these don't work properly on Windows, since stdout and stdin use "text" mode by default, which automatically transforms line endings. Switching them to binary mode corrects the problem.
I've done so after the call to `parse_args`, since the `-v` option prints version information to stdout, and this should be done in text mode.
> Use binary mode for stdin and stdout on Windows

- support/faad2-hdc-support.patch
Audio packets are protected by an 8-bit CRC, so it occasionally happens (in low-SNR scenarios) that corrupt packets make it past the CRC check and into the decoder.
In faad2, there are several code paths that initialize the SBR decoder (`sbrDecodeInit`) but only one of them sets the `Is_HDC_SBR` flag to 1 (in the `hdc_sbr_data_block` function). If a corrupt packet is the first to arrive, it may send faad2 down one of the other code paths that call `sbrDecodeInit`, leaving `Is_HDC_SBR` set to 0 instead. The flag is never updated, so the decoder will remain in the wrong state from that point on, causing garbled audio output.
To solve this, I modified `hdc_sbr_data_block` so that it sets `Is_HDC_SBR` to 1 on every invocation, rather than doing so only at the time that the SBR decoder is …
> Set Is_HDC_SBR on every invocation of hdc_sbr_data_block

- src/acquire.c
- src/decode.c
- src/decode.h
- src/defines.h
- src/frame.c
- src/frame.h
- src/input.c
- src/input.h
- src/main.c
- src/output.c
- src/output.h
- support/cli.py
Replaces #343.
Fixes #177.
Fixes #261.
Fixes #330.
The NRSC-5 standard uses a variable-rate audio codec. To account for variations in the instantaneous bit rate, the standard specifies that both the transmitter and receiver use an elastic buffer, so that audio packets enter the transmitter and leave the receiver at a fixed rate, even though the number of packets sent in individual audio PDUs may vary. Unfortunately, the standard does not explain how elastic buffering is implemented, so we are left to guess many of the details.
Up until now, nrsc5 did not implement elastic buffering at all, and instead reported audio packets through its API immediately upon decoding. In this PR I have added elastic buffers (one per stream) which queue audio packets. A batch of audio packets (2 for FM, 4 …
> Implement elastic buffering for audio output

- include/nrsc5.h
- src/frame.c
- src/frame.h
- src/main.c
- src/nrsc5.c
- src/private.h
- support/cli.py
- support/nrsc5.py
Fixes #374.
Fixes #398.
Neither SIS audio descriptors nor SIG are mandatory, leaving applications with no reliable way to know of the existence of an audio program. Audio PDU headers are always present, and convey useful information about audio programs, so I think it makes sense to expose this information through the API.
Here I've added a new event (`NRSC5_EVENT_AUDIO_SERVICE`) which exposes ~a linked list of~ audio services. The following information is available:
* program number
* access (public / restricted)
* program type
* codec mode
* blend control
* digital audio gain
* digital audio delay
* codec latency
The C & Python API clients display this information on "Audio service" lines:
```
16:16:36 Audio service 0: PUBLIC, type: Adult Hits, codec: 0, blend: ENABLE, gain: 0 dB, …
```
> Report information from audio PDU headers

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- src/pids.c
- src/private.h
- support/cli.py
- support/nrsc5.py
Fixes #405.
Here I've deprecated the SIS event and broken it down into eight smaller events:
* Station ID
* Station Name
* Station Slogan
* Station Message
* Station Location
* Audio Service Descriptor
* Data Service Descriptor
* Emergency Alert
Doing so has already helped remove a lot of redundant log messages from the C and Python CLI applications.
Before:
```
14:05:03 Synchronized
14:05:03 Country: CA, FCC facility ID: 328
14:05:03 Station name: MOVE-FM
14:05:03 Country: CA, FCC facility ID: 328
14:05:03 Station name: MOVE-FM
14:05:03 Audio program 0: public, type: Adult Hits, sound experience 0
14:05:03 Data service: public, type: Image Maps, MIME type e96
14:05:03 Country: CA, FCC facility ID: 328
14:05:03 Station name: MOVE-FM
14:05:03 Station location: 99.2146, -11.9686, 128m …
```
> Split up the SIS event

- src/pids.c
Reverts #406.
Altitude changes were annoying prior to #409 because each change would trigger a new SIS event, and the CLI apps would flood the console with repeated SIS data. But now that Station Location is split into its own event, it probably makes sense to faithfully report all SIS location data.
> Revert "Don't report altitude changes"

- src/nrsc5.c
- src/output.c
- src/output.h
- src/private.h
It looks like it's possible for a SIG table to have a duplicate entry. WHRV's SIG table has two entries for service number 2 (one without album art, and one with):
```
19:17:28 SIG Service: type=audio number=1 name=MPS
19:17:28   Audio component: id=0 port=0000 type=22 mime=4DC66C5A
19:17:28   Data component: id=1 port=07D0 service_data_type=265 type=3 mime=BE4B7536
19:17:28   Data component: id=2 port=07D1 service_data_type=265 type=3 mime=D9C72536
19:17:28 SIG Service: type=audio number=2 name=SPS1
19:17:28   Audio component: id=0 port=0001 type=0 mime=4DC66C5A
19:17:28 SIG Service: type=audio number=2 name=SPS1
19:17:28   Audio component: id=0 port=0001 type=0 mime=4DC66C5A
19:17:28   Data component: id=1 port=07D2 service_data_type=265 type=3 mime=BE4B7536
19:17:28   Data component: …
```
> Overwrite duplicate SIG services & components

- include/nrsc5.h
- src/CMakeLists.txt
- src/here_images.c
- src/here_images.h
- src/main.c
- src/nrsc5.c
- src/output.c
- src/output.h
- src/private.h
- support/cli.py
- support/nrsc5.py
Fixes #401.
Most of the details of the HERE Images stream were worked out in #308, so I've now added a decoder for it. Images are reported in `NRSC5_EVENT_HERE_IMAGE` API events, and logged by the C and Python command-line applications:
```
15:56:09 HERE Image: type=TRAFFIC, seq=2, n1=1, n2=9, time=2024-10-23T13:02:12Z, lat1=43.02372, lon1=-83.81881, lat2=42.82260, lon2=-83.54415, name=trafficMap_0_0_rdhs.png, size=3047
15:56:09 HERE Image: type=TRAFFIC, seq=2, n1=2, n2=9, time=2024-10-23T13:02:12Z, lat1=43.02372, lon1=-84.09347, lat2=42.82260, lon2=-83.26950, name=trafficMap_0_1_rdhs.png, size=4267
15:56:09 HERE Image: type=TRAFFIC, seq=2, n1=3, n2=9, time=2024-10-23T13:02:12Z, lat1=43.02372, lon1=-84.36813, lat2=42.82260, lon2=-82.99484, name=trafficMap_0_2_rdhs.png, size=5033
15:56:10 …
```
> Decode HERE Images

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- support/cli.py
- support/nrsc5.py
Replaces #419.
It makes sense to use a consistent time format across the libnrsc5 API. The LOT expiry time (added in #310) uses `struct tm`, while the HERE Images API (recently added in #415) uses a Unix timestamp. I propose to switch the HERE Images API over to `struct tm` to match the LOT API.
> Use struct tm to represent HERE Images time

- support/nrsc5.py
Fixes #423.
For security reasons, Python versions 3.8 and later no longer load DLL files from the PATH or the current directory:
https://docs.python.org/3/whatsnew/3.8.html#bpo-36085-whatsnew
At present, the only remaining option would be to install libnrsc5.dll to the system path. It would be convenient to allow the library to be loaded from the same directory as nrsc5.py, and this shouldn't increase the security risk unnecessarily.
> Allow loading libnrsc5.dll from the same directory as nrsc5.py on Windows

- src/CMakeLists.txt
- support/faad2-hdc-support.patch
Fixes #424.
To avoid accidentally exporting symbols, I've done two things here:
* build libnrsc5's shared and static versions separately, and only set `NRSC5_EXPORTS` for the shared version
* remove `__declspec(dllexport)` from faad2 in our patch; we're only building static libraries so it's not needed
With these changes, nrsc5.exe no longer has the spurious exports which were causing libnrsc5.dll.a to be overwritten.
I know very little about CMake & software builds, so I'd appreciate feedback on the approach.
> Avoid exporting from static libraries & executables

- src/main.c
- support/cli.py
Currently the C CLI defaults to the "trace" debug level (0) while the Python CLI defaults to "debug" (1).
Logging is starting to get noisy, particularly with the addition of stream & packet events in #308. The arrival of raw stream & packet data is of little interest to users; decoded data like HERE Images (#415) is far more interesting. So I think it would make sense to drop the log level for these events to "debug" (1), and make the CLI apps' default logging level "info" (2).
This change won't affect anything other than stream & packet events, since the CLI apps do not currently log anything at the "trace" or "debug" levels.
To see stream & packet events, simply use the `-l 1` argument to set the log level to "debug".
> Set default log level to info, and log stream & packet events at the debug level

- src/output.c
LOT fragments can either have a short header (with sequencing information only) or a long header (with sequencing information and file metadata). It just so happens that most stations use a long header for fragment 0 and a short header for all others, but this is not a requirement. The current parsing code assumes this is always the case, and uses the fragment sequence number to determine whether the header is short or long. We should instead determine that by checking the `hdrlen` field.
> Use hdrlen to check for LOT metadata header

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- src/output.c
- src/private.h
- support/cli.py
- support/nrsc5.py
After the addition of `service` and `component` fields in #414, the `port` field in stream, packet, and LOT events is now redundant. Thus, I think it would make sense to deprecate it and suggest `component->data.port` as a replacement.
> Deprecate the port field in stream/packet/LOT events

- src/output.c
- src/output.h
libnrsc5's LOT receiver can track up to 12 simultaneous file downloads per port. When a new LOT ID is seen, the least-recently-used LOT id is removed from the table of in-progress downloads to make space for a new one.
Currently, a static variable (`counter`) is incremented each time a LOT fragment arrives, and its value is stored in the corresponding LOT file struct. This value is used to determine which LOT ID is the least recently used. Unfortunately the static variable is shared across all `nrsc5_t` instances. Using a static variable without synchronization could lead to Undefined Behaviour in multi-threaded programs. To solve the problem, I propose to replace the static variable with a member variable in the `output_t` struct, which will be separate for each `nrsc5_t` instance.
> Refactor LOT LRU counter

- include/nrsc5.h
- src/main.c
- src/nrsc5.c
- src/private.h
- support/cli.py
- support/nrsc5.py
Partially addresses #372.
Information about RTL-SDR automatic gain selection is only reported via library debug messages. Client applications are interested in this information, so it would make sense to expose it through an API event instead.
I've updated the C and Python CLI applications to display the best gain value at the "info" level, and the intermediate gain values at the "debug" level. (Use the `-l 1` argument to see them.)
```
19:43:56 Gain: 25.4 dB, Peak amplitude: -12.7 dBFS
19:43:56 Gain: 38.6 dB, Peak amplitude: 0.0 dBFS
19:43:56 Gain: 32.8 dB, Peak amplitude: -6.0 dBFS
19:43:56 Gain: 28.0 dB, Peak amplitude: -9.6 dBFS
19:43:56 Gain: 29.7 dB, Peak amplitude: -8.5 dBFS
19:43:56 Best gain: 29.7 dB, Peak amplitude: -8.5 dBFS
```
> Report AGC status in an API event

- README.md
A simple change to the readme. Added IQ files to the first paragraph in the readme so it's a bit more clear that this isn't only just for the rtl-sdr. 
Maybe we need to include the required sample rate too?
> Add IQ files to the first paragraph in the readme. 
