src/sync.c

I think the MER dB calculation is off by a factor of 2. That can be corrected by removing the square roots.

Fix MER calculation.

---

CMakeLists.txt
src/CMakeLists.txt
src/frame.c
src/frame.h
src/input.c
src/input.h
src/output.c
src/output.h

Added parsing of ID3 from PSD.  Uses external id3v2lib to parse once a complete PSD has been grabbed.  ID3 tags are sent to the console output for display.

Parsing and display of program service description

---

src/CMakeLists.txt
src/conv.h
src/conv_dec.c
src/decode.c
src/decode.h
src/defines.h
src/frame.c
src/frame.h
src/pids.c
src/pids.h
src/sync.c

This adds support for receiving service mode MP3, which adds two extra partitions to each band.
I've tested this with four stations using service mode MP3, and was able to receive the HD3 channel for each of them.
This branch builds on the work started in #28.

Add support for service mode MP3.

---

src/CMakeLists.txt
src/conv.h
src/conv_dec.c
src/decode.c
src/decode.h
src/defines.h
src/frame.c
src/pids.c
src/pids.h

This partly addresses #24. Message types 2 through 9 still need to be implemented; I'll carry on with those soon.
SIS is described here: http://www.nrscstandards.org/sg/nrsc-5-c/1020si.pdf
/cc @pclov3r

Add partial PIDS / SIS implementation.

---

README.md

I did a minimal Debian 9 netinst to check what packages are actually necessary to build, and updated the list accordingly.

Add necessary Debian packages.

---

CMakeLists.txt
README.md
src/CMakeLists.txt
src/acquire.c
src/config.h.in
src/conv_dec.c
src/conv_sse.h
src/defines.h
src/firdecim_q15.c
src/frame.c
src/input.c
src/log.c
src/main.c
src/math.c
src/output.c
src/output.h
src/resamp_q15.c
src/strndup.c
src/sync.c
src/sync.h

@awesie Time to merge the experimental branch into master? It's been working well for me.

Merge experimental branch

---

src/pids.c
src/pids.h

This builds on #57 and gets further towards implementing #38. Here I've implemented SIS message types 2 (long station name) and 4 (station location).
Some stations put useful information in these fields, but others leave them set to default, placeholder values.
@itdaniher

Implement long station name & station location.

---

src/output.c

This log message is very noisy, so I'd like to remove it for now.

Quiet logging in process_port.

---

CMakeLists.txt
README.md
src/main.c

This partially addresses #60.
/cc @classicjazz

Add -v option that prints the git revision.

---

src/frame.c

There was a lot of duplication between `frame_process` and `find_program`, so I decided to merge them. This will also open up the possibility of having `frame_process` deal with multiple programs, for instance so that multiple programs can be saved to disk or streamed simultaneously.
`frame_process` now parses the frame in a single pass from beginning to end. While I was at it, I made some other improvements:
* proper HEF parsing (in `parse_hef`)
* additional length checks for robustness
* simplified `parse_location` by passing in the start of the location bytes.

Refactor frame_process.

---

README.md

Fixes #93.
I've updated the usage examples to begin with the simplest possible invocation (which should be suitable for most users), and added explanations for each of the examples.
How does this look @pclov3r @impala454?

Add more detail to usage examples.

---

src/frame.c
src/frame.h
src/input.c
src/input.h
src/output.c
src/output.h

I've changed `frame_process` to process all programs, and moved the decision about which program to play into the output component. That will make it easier to output multiple programs in the future.

Process all programs in frame_process.

---

src/output.c

Currently, only TIT2 (title), TPE1 (artist) and TALB (album) ID3 tags are decoded. This PR adds decoding for three additional tags:
* TCON (genre)
* UFID (unique file identifier)
* COMR (commercial)
It also prints out the raw bytes of any other tags. In my set of 40 recordings, only the XHDR tag cannot be decoded. XHDR is used for album art synchronization (according to this article: http://www.radioworld.com/digital-radio/0014/artist-experience-and-album-art-via-hd-radio/330814), and so reverse engineering it may help with #115.

Decode more ID3 tag types.

---

src/pids.c

This change fixes parsing of the station location. The old code treated the coordinates as an unsigned integer with a sign bit. However, coordinates are actually sent as 22-bit, two's complement signed integers.
This seems to fix the reported location of several stations, although there are still a few that still report bogus locations. However, as far as I can tell, this is a problem with those stations -- the raw bits do not make any sense when manually decoded.

Fix station location parsing

---

src/pids.c

@supersat I realized after merging #132 that the sign extension calculation was incorrect (because it sets the last bit to one). It also occurred to me that the two's complement calculation may as well live in its own function (which I've named `decode_signed_int`).
The new function works by subtracting 2^n from the integer if the high bit is set to 1.

Fix and simplify two's complement calculation.

---

src/acquire.c
src/acquire.h
src/firdecim_q15.c
src/firdecim_q15.h
src/input.c
src/nrsc5.c
src/output.c
src/output.h
src/sync.c
src/sync.h

This commit should fully reset the various data structures whenever the API user wants to change stations.

Reset state after changing frequency.

---

.travis.yml
support/nrsc5.py

It might be useful to merge in my prototype Python CLI app at this point. it's already helping to test the API, and it can be executed as part of Travis CI so help us catch bugs earlier. (For instance in `nrsc5_open_pipe` and `nrsc5_pipe_samples`, which are not used by the C CLI app.)

Prototype a Python CLI app.

---

.travis.yml

Cross-compiling from OSX to Windows worked just fine in CI: https://travis-ci.org/argilo/nrsc5/builds/488220528
I've rebased to resolve a merge conflict, and will merge once the new build passes CI.

Cross-compile from OSX to Windows during CI.

---

README.md

I added a short description of nrsc5 at the top, put all the build instructions together after that, and added cross-compilation instructions. Suggestions welcome.

Update and reorganize the readme.

---

src/output.c

Some stations do not broadcast XHDR tags. In that case, the values in the `xhdr` struct are left uninitialized, and garbage data is sent out to the callback function. To fix this, I initialized them a the top of `output_id3`, just like all the other ID3 parameters.

Initialize XHDR values.

---

src/defines.h
src/sync.c

I've carried on removing magic numbers, this time in sync.c.

Remove more magic numbers.

---

support/cli.py
support/nrsc5.py

These changes improve the pylint rating for nrsc5.py from 5.62 to 7.91, and cli.py from 7.21 to 9.03.

Reduce the number of pylint warnings.

---

src/sync.c

Fixes #221.
As noted in https://github.com/theori-io/nrsc5/issues/221#issuecomment-643716708, CFO synchronization uses two specific reference subcarriers. If either of those subcarriers is missing (due to interference or multipath), then the entire synchronization process fails.
To fix this, I've changed the CFO synchronization routine to take into account all 22 reference subcarriers in the Primary Main (PM) sidebands. If at least three of them are found to have the same offset, then we assume that we've found the correct synchronization parameters.

Consider all reference subcarriers when detecting CFO

---

README.md

Document keyboard commands

---

src/pids.c

This pull request makes several improvements to the robustness of PIDS decoding:
1. Stop decoding if an unknown MSG ID is encountered. There's no safe way to continue, since we don't know what the payload size should be.
2. Stop decoding if the payload size is greater than the number of remaining bits.
3. Report the updated station location if the altitude changes.
4. Add support for Advanced Service Information Message, added in NRSC-5-E. (Its content is identical to Service Information Message).
5. Initialize FCC facility ID to -1, consistent with other integer values.

Improve robustness of PIDS decoding

---

src/frame.c

While working on #306, I noticed that parsing of the Synchronization Channel is lax, and not entirely correct:
* Both nibbles of the "count" byte are supposed to be equal. Verifying this will add some robustness in the face of errors.
* The count value 0x00 is treated as a special case, which indicates that the CCC width is one. This special case needs to be handled separately.
After these changes, all data files in my sample set still decoded correctly.

Process the synchronization channel more strictly

---

src/nrsc5.c

This is an alternative to #325.
As noted there, if `nrsc5_start` is accidentally called after entering pipe mode with `nrsc5_open_pipe`, then the (unnecessary) worker thread enters into a busy loop. Here I've updated the API functions to skip all worker thread code in the pipe mode, so that API users can safely call `nrsc5_start` regardless of the mode. It will simply do nothing in the pipe mode.

Don't touch the worker thread in pipe mode

---

support/cli.py

Fixes #361.
See that issue for a description of the problem and the approaches I tried to solve it.

Handle Ctrl+C better in the Python CLI

---

src/sync.c

Fixes #318.
Reference subcarriers are mainly used for synchronization, but they also convey some important data fields (L1 block count, primary service mode, advanced service mode, secondary channel indicator). Because the data fields are not protected by FEC, errors can creep in, especially when SNR is low.
To ensure correct decoding of the block count value, nrsc5 requires the value to agree across several reference subcarriers. But there is no such check for the primary service mode, and the decoded value is prone to corruption. I've added a check here, and the primary service mode is now decoded correctly for all my I/Q recordings. The total number of decoded audio packets also increased by 0.23%.
Also, the `decode_ref_fm` function now returns the block count value, instead of …

Make reference subcarrier decoding more robust

---

src/nrsc5.c

In #370, automatic gain selection was changed to measure only the amplitude at the ADC. Since the relationship between gain and amplitude is monotonic, there's no reason to check every gain value, and we can speed things up with a binary search.
For the R820T tuner, no more than 5 gain values need to be checked (vs. 29 before).

Speed up automatic gain selection with binary search
